### ISSUE TITLE
There is no Upgrade doc

### ISSUE THREAD

**Issue by sandyg1** [pivotal-cf/docs-mysql#169]
There is no upgrade doc which describes the steps and more importantly documents if there is downtime expected when doing an upgrade.

**Comment by sandyg1** [comment]
Is downtime expected while an upgrade happens?

**Comment by pspinrad** [comment]
Converted interruptions.html topic with info on downtime into more general upgrade topic for v2.0 docs: http://docs-pcf-staging.cfapps.io/p-mysql/2-0/upgrade.html
