### ISSUE TITLE
max_user_connections on restarting an application

### ISSUE THREAD

**Issue by gouthamvasireddi** [pivotal-cf/docs-mysql#242]
I'm using a spring boot application with on demand mysql database provided by pcf.

When ever I'm restarting my spring boot application. I'm get following errors.

Looks like there is issue in pcf or spring.io to release the connections even when an application is stopped and being restarted.

Please let me know if I'm missing anything.

Following are the major error logs
o.s.c.s.r.PooledDataSourceCreator : Found Tomcat JDBC connection pool on the classpath. Using it for DataSource connection pooling.
 [ main] o.a.tomcat.jdbc.pool.ConnectionPool : maxIdle is larger than maxActive, setting maxIdle to: 30

[OUT] java.sql.SQLSyntaxErrorException: Could not connect: User 'ZZZZ' has exceeded the 'max_user_connections' resource (current value: 40)

**Comment by jncd** [comment]
@menicosia and @mfine30 Can either of you help with this issue?

**Comment by jncd** [comment]
Hello @gouthamvasireddi   
I discussed this issue with the PMs for the MySQL for PCF product. They believe that this is a spring boot issue, not a problem with the documentation set for the MySQL for PCF. 
I have found the issue channel for spring boot:  
https://github.com/spring-projects/spring-boot/issues
You should ask your question there. 
Thanks!
