### ISSUE TITLE
Some customer confusion due to PCF 2.x not being mentioned here

### ISSUE THREAD

**Issue by ppickett-pivotal** [pivotal-cf/docs-mysql#288]
https://github.com/pivotal-cf/docs-mysql/blob/e4c764781150559fb3901866dff94b92bcb95d36/release-notes.html.md.erb#L66

There has been some customer confusion due to PCF 2.x not being mentioned here. For consistency with the v1 Release Notes, maybe this should be something like:

```
MySQL for PCF v2.2 requires PCF v1.12 or later or PCF v2.0 or later.
```

**Comment by bentarnoff** [comment]
Thanks for bringing this to our attention, @ppickett-pivotal. We've clarified the release notes along the lines you recommended. The change should be live soon.
