### ISSUE TITLE
Missing configuration step

### ISSUE THREAD

**Issue by parth-pandit** [pivotal-cf/docs-mysql#289]
There is no mention of **Errands** configuration in this document that should be there.

**Comment by jncd** [comment]
Hi @parth-pandit Would you be able to tell us which version of the doc and which page this applies to?

**Comment by jncd** [comment]
Hi @parth-pandit 
We see that the v2.x docs do not discuss configuring errands. We'll make a story to add that section. Thanks!

**Comment by parth-pandit** [comment]
Thanks for taking care of this. However, I see that the issue is closed. So, do you close the issue without the solution in place yet? I see my such other issues marked as "scheduled" but not closed.

Regards,
Parth Pandit
Java & AWS Solution Architect
http://www.linkedin.com/in/parthpandit
Phone: +1 (470) 422-6629
________________________________

**Comment by bentarnoff** [comment]
@parth-pandit We've created a new story to take care of documenting the Errands section. You can find it here: https://www.pivotaltracker.com/n/projects/1964915/stories/157695380. And feel free to contact us on the Pivotal Slack at #pcf-docs if you have any further questions or concerns.
