### ISSUE TITLE
Enable TLS on mysql 2.4.x doesn't have example with BOSH DNS hostnames

### ISSUE THREAD

**Issue by aegershman** [pivotal-cf/docs-mysql#301]
The [Enable TLS](https://docs.pivotal.io/p-mysql/2-4/using-tls.html#enable-tls) section of the documentation uses static IPs for hostnames when enabling TLS. However, mysql 2.4.x+ uses BOSH DNS for name resolution, so instead of `"hostname": "10.1.16.3"`, you'll see `"hostname": "q-n2s3y1.q-g13347.bosh"`.

Or in the case of a leader-follower topology, you'll see:

```
  "hostname": "q-n2s3y1.q-g13347.bosh",
  "hostnames": [
    "q-m14289n2s0.q-g13347.bosh",
    "q-m14288n2s0.q-g13347.bosh"
  ],
```

I am confused on a few fronts:

1. how should I enable TLS on these service instances using bosh dns? I'm assuming it's `cf update-service db-leader-follower -c '{"enable_tls": ["q-n2s3y1.q-g13347.bosh"]}'
2. how should I enable TLS on service instances using bosh DNS that are also leader-follower? In the above configuration, it's a leader-follower topology. What should my `update-service` string look like?
3. Is it possible to **DISABLE** TLS after a service-instance has been enabled?

Thanks for your time

**Comment by aegershman** [comment]
Also, in the doc it says if you are using leader-follower topology, you should include a list of the `hostnames`. But when we do that, we get a not-so-encouraging error message:

```
cf update-service db-leader-follower -c '{"enable_tls": ["q-m14289n2s0.q-g13347.bosh", "q-m14288n2s0.q-g13347.bosh"]}'

Updating service instance db-leader-follower as Aaron.Gershman@cerner.com...

FAILED

Server error, status code: 502, error code: 10001, message: Service broker error: the 'enable_tls' option must be supplied exactly one address
```

It would be helpful if the documentation included some examples to clarify what's expected with BOSH DNS.

**Comment by menicosia** [comment]
Hi there @aegershman,

While looking at your other PR (thank you!), I noticed that we hadn't updated this issue. It's already been prioritized and is making it way up the backlog. When a docs writer picks it up, they may come back here (or talk to us on the product side) for clarifications!

Thank you, we won't waste your effort.

**Comment by radaeze** [comment]
@aegershman Thanks for your feedback! We have updated the docs to reflect the changes with BOSH DNS: https://docs.pivotal.io/p-mysql/2-4/using-tls.html#enable-tls . To answer your third question you cannot disable TLS once it is enabled. We planning to call this out in the docs.

**Comment by aegershman** [comment]
Thank you @radaeze I appreciate it && I appreciate the work you all do-- it's objectively making our lives as developers and operators better 👍
