### ISSUE TITLE
If backups can only be restored to single-node plans, docs should make larger mention of that

### ISSUE THREAD

**Issue by aegershman** [pivotal-cf/docs-mysql#302]
As an operator hardening their backup/recovery process, it's important to know [that backups can only be restored to a single-node plan](https://docs.pivotal.io/p-mysql/2-4/backup-and-restore.html#restoreinstance):

> Note: You can only restore to a single-node plan. Therefore, in this procedure the new service instance you create for restore uses a single-node plan. If you are restoring to a leader-follower plan, you can update the plan on the new service instance after you run the restore utility. This is included in the instructions in Run the Restore Utility below.

This is significant to us because currently all the plans in our foundations are `leader-follower`. [Maybe it's in the install doc and I missed it, but it would be helpful to know this when configuring plans](https://docs.pivotal.io/p-mysql/2-4/install-config.html)

(Thanks for your time!)

**Comment by menicosia** [comment]
Thanks Aaron! We'll work with docs to make sure this get prioritized!

**Comment by aegershman** [comment]
Apologies if these issues/comments come off as obnoxious (especially since I don't even offer the fixes as a PR, what a prick). Don't mean to be a bother. Thanks a ton for your work & responsiveness 👍

**Comment by radaeze** [comment]
Thanks @aegershman! We added a note to the installing topic: https://docs.pivotal.io/p-mysql/2-4/install-config.html#active

**Comment by aegershman** [comment]
Thank you @radaeze I appreciate it!

Also not to be annoying but something that just caught my eye is this `<:/strong>` tag: https://github.com/pivotal-cf/docs-mysql/blob/2.4/install-config.html.md.erb#L206 I think it should be `</strong>` (without semicolon) because it's improperly rendering in the UI.

**Comment by jncd** [comment]
Thanks, @aegershman for spotting the html issue. 
Fixed now, though you might need a hard refresh to see it.
