### ISSUE TITLE
mysql product api

### ISSUE THREAD

**Issue by prdev1** [pivotal-cf/docs-mysql#309]
Dears, 

I use the below JSON to create a new plan mysql :

```
{
         "properties": {
           ".properties.plan_collection": {
             "value": [
               {
                 "name": {"value": "microplan"},
                 "description": {"value": "Micro Service Plan (10mb)"},
                 "max_storage_mb": {"value": "10"},
                 "max_user_connections": {"value": "10"},
                 "private": {"value": "true"}
               }
             ]
           }
         }
}
```

But, it always throws back this error : 
```
{"errors":{".properties.plan_collection":["Record 1: Name can't be blank","Record 1: Name must only contain lowercase letters, numbers, hyphen(-), or underscore(_)","Record 1: Description can't be blank","Record 1: Max Storage Mb can't be blank","Record 1: Max User Connections can't be blank"]}}
```

the curl I used is : 

```curl -k "https://opsmanager.domain.com/api/v0/staged/products/p-mysql-50e42f2a0862baa9827a/properties" -H "Authorization: bearer $accesstoken" -H "Content-Type: application/json" -X PUT -d @microplan.json```

What is wrong with my JSON ? I follow this : https://docs.pivotal.io/pivotalcf/2-0/opsman-api/#updating-a-collection-property

**Comment by jncd** [comment]
@menicosia @jzlwang @scribblingfox 
This is a problem with the opsman API docs. 
Do you know who's responsible for these docs?
Also, how can prdev1 get help for the issue? ('Maybe contact support before the docs get fixed?)

**Comment by jncd** [comment]
Hi Sarah 
I just realized this is still in my tracker... Not sure where to move it. 
It seems to be for the Ops Man API docs... Which team deals with those?
TIA, jane

**Comment by mlimonczenko** [comment]
@prdev1 

Thank you for raising this issue, and I'm sorry that you are having trouble. Please sign in to [Pivotal Support](https://support.pivotal.io) and consult the community or open a case. See [Pivotal Support for Subscribers](https://content.pivotal.io/support/pivotal-support-for-subscribers) for how to do this.  
      If Pivotal Support's investigation determines that this is a general problem, rather than an issue that is fairly specific to your situation, we will update the documentation.
