### ISSUE TITLE
rabbitmq screenshot for mysql docs

### ISSUE THREAD

**Issue by pakiheart** [pivotal-cf/docs-mysql#314]
Screenshots on the docs show rabbitmq not mysql

**Comment by pakiheart** [comment]
yes

**Comment by radaeze** [comment]
Okay. Thanks for the feedback. The RabbitMQ screenshot is meant to be an example of the `Global Service Plan Configuration` page. The content of the page is the same for MySQL except for the RabbitMQ header as mentioned in the note. However, he was working on making the screenshot more generic to avoid confusion.
