### ISSUE TITLE
Troubleshooting persistent disk full could include deleting old mysql-binlogs

### ISSUE THREAD

**Issue by aegershman** [pivotal-cf/docs-mysql#318]
As an operator, in order to recover instances with full persistent disks, it would be helpful for the troubleshooting guide to suggest deleting an old binlog from `/var/vcap/store/mysql/data` to free up space.

## background

One of our customer's mysql (2.5, leader-follower) instances had their persistent disk fill to 99%.

In order to upgrade the instance to a larger plan, we had to `bosh ssh` onto the VM and purge audit logs, [as described in the troubleshooting documentation](https://docs.pivotal.io/p-mysql/2-5/troubleshoot.html#persistent-disk). Unfortunately, that didn't clear off enough room.

We received a suggestion from support (case num 196363) to delete an old binlog on both the leader & follower from `/var/vcap/store/mysql/data` (e.g., `mysql-bin.000003`, etc), as they were taking up ~513MB each.

This was a great suggestion and deleting just one gave the instance enough room to successfully terminate && allowed the instance to upgrade to a larger plan.

Although in an ideal world an instance could be upgraded to a larger plan without operator involvement, in this world it would have been helpful to have that included in the documentation. Or perhaps in a community knowledge-base article?

Thanks for your time and consideration!

**Comment by radaeze** [comment]
@aegershman Thanks for this! I talked to @menicosia about this and we are updating the docs to reflect the support suggestion.

**Comment by aegershman** [comment]
Of course, not a problem. Granted, I say this as a suggestion but have _genuinely no idea_ whether there are ramifications for deleting the old mysql-binlogs, so hopefully it doesn't burn anyone? ¯\\_(ツ)_/¯

Thanks again for all you all do 👌 it helps us sleep better at night. Please feel free to close this whenever.

**Comment by radaeze** [comment]
Sorry it took us so long to address this.  😱
