### ISSUE TITLE
Restore single SI doc doesn't tell user how to find encryption passphrase

### ISSUE THREAD

**Issue by menicosia** [pivotal-cf/docs-mysql#323]
https://github.com/pivotal-cf/docs-mysql/blob/2dc0006dfaf07fbd4cf3ca3681e39eec80ec2877/restoring-single-instance.html.md.erb#L40-L43

This step requires a passphrase. There should be a link to the [restoring](https://docs.pivotal.io/p-mysql/1-10/backup.html#restoring) section of the backups docs; getting the passphrase is covered in step 1.

**Comment by snneji** [comment]
Hi @menicosia, we added the info directly to the step because it is only one line so it would be too jarring for users to follow a link and come back http://docs-pcf-staging.cfapps.io/p-mysql/1-10/restoring-single-instance.html#restore. Let me know what you think and I can deliver the story.

**Comment by snneji** [comment]
cc: @Pivotal-Christopher-Wong

**Comment by menicosia** [comment]
Yeah! That looks good to me. I forgot that in MySQL v1, you can get to the credential simply.

From my perspective, you can close this issue.

**Comment by snneji** [comment]
Thanks @menicosia. We plan to pair with Judy to see if we can make a similar clarification to the v2 doc.
The restore instructions are a bit different in the v2 docs though.
