### ISSUE TITLE
v2.8 Data at Rest - Broken Link

### ISSUE THREAD

**Issue by nanda-dev** [pivotal-cf/docs-mysql#374]
The link provided in the 'More Information' column for 'Encrypted Data at Rest' seems to be broken, and results in a 'Page not Found' error page. 
Here's is the link in question:
```
<td><a href="https://docs.pivotal.io/partners/vormetric-transparent-encryption/">Thales Vormetric plugin</a></td>
```
Did this doc page get moved/renamed? Will be good to have a valid link here that provides helpful info on how to achieve Data at Rest encryption for MySQL DB instances provisioned from the Marketplace.

**Comment by snneji** [comment]
Hi @nanda-dev, sorry for not getting back to you earlier. The Thales Vormetric plugin service is no longer available. I am currently looking into whether we can replace the link with another suggestion for encryption at rest.

**Comment by nanda-dev** [comment]
@snneji - sure, no problem! Thanks for taking a look!

**Comment by snneji** [comment]
Hi @nanda-dev, unfortunately there is currently no tested integration for encryption at rest with the MySQL tile, so we cannot make a recommendation. We will be removing the row from the table. Thank you for flagging this issue.
